[package]
name = "qingyin-testkit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
qingyin-admission.workspace = true
qingyin-contract.workspace = true
qingyin-provider.workspace = true
qingyin-state.workspace = true
qingyin-types.workspace = true

[lints]
workspace = true
