//! Canonical IDs, lifecycle values, errors, events, and trace-safe primitives.

use std::fmt;

use serde::de::Error as _;
use serde::{Deserialize, Deserializer, Serialize};

/// Stable fixture schema version for the first public contract generation.
pub const SCHEMA_VERSION_V1: &str = "v1";

const RESOURCE_ID_MIN_LENGTH: usize = 8;
const RESOURCE_ID_MAX_LENGTH: usize = 128;

/// Validated opaque identifier shared by public resource ID wrappers.
#[derive(Clone, Debug, Eq, Hash, PartialEq, Serialize)]
#[serde(transparent)]
pub struct ResourceId(String);

impl ResourceId {
    /// Creates an ID when it satisfies the frozen OpenAPI length bounds.
    #[must_use]
    pub fn new(value: impl Into<String>) -> Option<Self> {
        let value = value.into();
        (RESOURCE_ID_MIN_LENGTH..=RESOURCE_ID_MAX_LENGTH)
            .contains(&value.len())
            .then_some(Self(value))
    }

    /// Returns the identifier as a string slice.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl<'de> Deserialize<'de> for ResourceId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Self::new(value).ok_or_else(|| D::Error::custom("resource ID length must be 8..=128"))
    }
}

impl fmt::Display for ResourceId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

macro_rules! typed_resource_id {
    ($(#[$metadata:meta])* $name:ident) => {
        $(#[$metadata])*
        #[derive(Clone, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
        #[serde(transparent)]
        pub struct $name(ResourceId);

        impl $name {
            /// Creates a typed ID after applying the public resource ID constraints.
            #[must_use]
            pub fn new(value: impl Into<String>) -> Option<Self> {
                ResourceId::new(value).map(Self)
            }

            /// Returns the identifier as a string slice.
            #[must_use]
            pub fn as_str(&self) -> &str {
                self.0.as_str()
            }

            /// Returns the validated resource ID without discarding its semantic type.
            #[must_use]
            pub fn as_resource_id(&self) -> &ResourceId {
                &self.0
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
                formatter.write_str(self.as_str())
            }
        }
    };
}

typed_resource_id!(
    /// Public QingYin session identifier.
    SessionId
);
typed_resource_id!(
    /// Globally unique canonical event identifier.
    EventId
);
typed_resource_id!(
    /// Cross-service trace identifier.
    TraceId
);
typed_resource_id!(
    /// Public request correlation identifier.
    RequestId
);
typed_resource_id!(
    /// Opaque identifier for access-controlled diagnostics.
    DiagnosticId
);

/// Milliseconds since the Unix epoch, generated by the service.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(transparent)]
pub struct TimestampMs(pub u64);

/// Sequence number that is strictly increasing inside one session event stream.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(transparent)]
pub struct EventSequence(pub u64);

/// Public task families. A task is independent from its transport/session mode.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum TaskKind {
    /// Automatic speech recognition.
    Asr,
    /// Text-to-speech synthesis.
    Tts,
    /// Realtime ASR, model, and TTS orchestration.
    Realtime,
}

/// Public session execution mode from the control API.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SessionMode {
    /// Incremental input or output over a streaming transport.
    Streaming,
    /// Bidirectional low-latency realtime interaction.
    Realtime,
    /// One request produces one bounded result stream.
    OneShot,
}

/// Audio codec values frozen in the control API v1 contract.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum AudioCodec {
    /// Opus compressed audio.
    Opus,
    /// MPEG Layer III compressed audio.
    Mp3,
    /// Signed 16-bit little-endian PCM.
    #[serde(rename = "pcm_s16le")]
    PcmS16Le,
}

/// Audio container values frozen in the control API v1 contract.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum AudioContainer {
    /// Ogg container.
    Ogg,
    /// WebM container.
    WebM,
    /// Headerless codec frames.
    Raw,
    /// MPEG container or elementary stream.
    Mpeg,
}

/// Canonical audio format negotiated at the public contract boundary.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct AudioSpec {
    /// Audio codec.
    pub codec: AudioCodec,
    /// Optional stream or file container.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub container: Option<AudioContainer>,
    /// Sample rate in hertz.
    pub sample_rate_hz: u32,
    /// Channel count.
    pub channels: u8,
    /// Optional frame duration in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub frame_ms: Option<u16>,
}

impl AudioSpec {
    /// Validates numeric bounds that cannot be represented by the v1 enums.
    #[must_use]
    pub fn is_valid_for_v1(&self) -> bool {
        matches!(self.sample_rate_hz, 8_000 | 16_000 | 24_000 | 48_000)
            && matches!(self.channels, 1 | 2)
            && self
                .frame_ms
                .is_none_or(|frame_ms| (10..=200).contains(&frame_ms))
    }
}

/// Internal session state used to enforce the canonical lifecycle.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SessionState {
    /// Request identity exists but authorization has not completed.
    Created,
    /// Principal and resource ownership were validated.
    Authorized,
    /// Side-effect-free route filtering and scoring is in progress.
    Routing,
    /// Capacity is reserved and the lease is durable.
    Leased,
    /// The selected data-plane channel is being established.
    Connecting,
    /// The session can accept or emit media.
    Active,
    /// New input is closed while accepted work finishes.
    Draining,
    /// A recoverable boundary is being re-established.
    Retrying,
    /// The session completed normally.
    Completed,
    /// The client or service cancelled the session.
    Cancelled,
    /// The lease or session lifetime elapsed.
    Expired,
    /// The session ended with a canonical error.
    Failed,
}

impl SessionState {
    /// Returns whether no later state may replace this state.
    #[must_use]
    pub const fn is_terminal(self) -> bool {
        matches!(
            self,
            Self::Completed | Self::Cancelled | Self::Expired | Self::Failed
        )
    }

    /// Checks one forward transition from the frozen module 01 state machine.
    #[must_use]
    pub const fn can_transition_to(self, next: Self) -> bool {
        if self.is_terminal() {
            return false;
        }

        if matches!(next, Self::Cancelled | Self::Expired | Self::Failed) {
            return true;
        }

        matches!(
            (self, next),
            (Self::Created, Self::Authorized)
                | (Self::Authorized, Self::Routing)
                | (Self::Routing, Self::Leased)
                | (Self::Leased, Self::Connecting)
                | (Self::Connecting, Self::Active)
                | (Self::Active, Self::Draining | Self::Retrying)
                | (Self::Retrying, Self::Active)
                | (Self::Draining, Self::Completed)
        )
    }
}

/// Initial status exposed by a newly created session lease.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum LeaseStatus {
    /// Reservation and durable lease exist.
    Leased,
    /// A data-plane connection is being prepared.
    Connecting,
    /// The client may start the negotiated stream.
    Ready,
}

/// Tenant-visible status exposed by the session summary API.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SessionStatus {
    /// Reservation and durable lease exist.
    Leased,
    /// A data-plane connection is being prepared.
    Connecting,
    /// Media may be sent or received.
    Active,
    /// Accepted work is completing after input closed.
    Draining,
    /// The session completed normally.
    Completed,
    /// The session was cancelled.
    Cancelled,
    /// The session lifetime elapsed.
    Expired,
    /// The session ended with an error.
    Failed,
}

/// Canonical error category from the module 12 error dictionary.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCategory {
    /// Authentication or authorization failure.
    Auth,
    /// Quota or rate-limit failure.
    Quota,
    /// Request validation failure.
    Validation,
    /// Policy denial.
    Policy,
    /// Session lifecycle failure.
    Session,
    /// Provider or upstream failure.
    Upstream,
    /// Capacity admission failure.
    Capacity,
    /// Internal service failure.
    Internal,
}

/// Canonical error code from the module 12 error dictionary.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    /// Invalid QingYin credential.
    AuthInvalid,
    /// The principal does not have the required permission.
    PermissionDenied,
    /// Tenant or provider quota was exhausted.
    QuotaExhausted,
    /// A request rate limit was exceeded.
    RateLimited,
    /// The requested task, codec, language, or profile is unsupported.
    UnsupportedCapability,
    /// The request schema or value is invalid.
    InvalidRequest,
    /// Audio encoding, order, or rate is invalid.
    InvalidAudio,
    /// A hard policy denied the request.
    PolicyDenied,
    /// A ticket or lease expired.
    SessionExpired,
    /// The provider is unavailable before a safe boundary.
    ProviderUnavailable,
    /// The provider exceeded its operation deadline.
    ProviderTimeout,
    /// The provider emitted invalid protocol data.
    ProviderProtocolError,
    /// Gateway or provider capacity is exhausted.
    CapacityExceeded,
    /// The session was cancelled.
    Cancelled,
    /// An unexpected internal error occurred.
    InternalError,
}

impl ErrorCode {
    /// Returns the only valid category for this code.
    #[must_use]
    pub const fn category(self) -> ErrorCategory {
        match self {
            Self::AuthInvalid | Self::PermissionDenied => ErrorCategory::Auth,
            Self::QuotaExhausted | Self::RateLimited => ErrorCategory::Quota,
            Self::UnsupportedCapability | Self::InvalidRequest | Self::InvalidAudio => {
                ErrorCategory::Validation
            }
            Self::PolicyDenied => ErrorCategory::Policy,
            Self::SessionExpired | Self::Cancelled => ErrorCategory::Session,
            Self::ProviderUnavailable | Self::ProviderTimeout | Self::ProviderProtocolError => {
                ErrorCategory::Upstream
            }
            Self::CapacityExceeded => ErrorCategory::Capacity,
            Self::InternalError => ErrorCategory::Internal,
        }
    }

    /// Returns whether a retry is safe before stage-specific context is available.
    #[must_use]
    pub const fn default_retryable(self) -> bool {
        matches!(
            self,
            Self::QuotaExhausted
                | Self::RateLimited
                | Self::ProviderUnavailable
                | Self::CapacityExceeded
                | Self::InternalError
        )
    }
}

/// Transport-neutral canonical error before an API request ID is attached.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CanonicalError {
    /// Stable canonical code.
    pub code: ErrorCode,
    /// Sanitized developer-facing message.
    pub message: String,
    /// Whether retry is safe for this occurrence.
    pub retryable: bool,
    /// Optional retry hint in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retry_after_ms: Option<u64>,
    /// Optional bounded scope such as a tenant, provider, or gateway gate.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    /// Optional reference to access-controlled diagnostic detail.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub diagnostic_id: Option<DiagnosticId>,
}

impl CanonicalError {
    /// Builds an error with canonical default retry behavior.
    #[must_use]
    pub fn new(code: ErrorCode, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
            retryable: code.default_retryable(),
            retry_after_ms: None,
            scope: None,
            diagnostic_id: None,
        }
    }

    /// Returns the category derived from the canonical code.
    #[must_use]
    pub const fn category(&self) -> ErrorCategory {
        self.code.category()
    }
}

/// Canonical event names shared by streaming transports and contract fixtures.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum EventType {
    /// The session may begin negotiated media transfer.
    #[serde(rename = "session.ready")]
    SessionReady,
    /// The session remains usable with reduced capability or quality.
    #[serde(rename = "session.degraded")]
    SessionDegraded,
    /// The session completed normally.
    #[serde(rename = "session.completed")]
    SessionCompleted,
    /// The session cannot continue because of a canonical error.
    #[serde(rename = "session.error")]
    SessionError,
    /// A recoverable flow-control limit is approaching.
    #[serde(rename = "flow.warning")]
    FlowWarning,
    /// New work is rejected with retry guidance.
    #[serde(rename = "flow.busy")]
    FlowBusy,
    /// A realtime model turn started.
    #[serde(rename = "llm.turn_started")]
    LlmTurnStarted,
    /// A realtime model emitted stable text delta data.
    #[serde(rename = "llm.text_delta")]
    LlmTextDelta,
    /// A realtime model requested a tool invocation.
    #[serde(rename = "llm.tool_call")]
    LlmToolCall,
    /// A realtime model turn completed.
    #[serde(rename = "llm.turn_completed")]
    LlmTurnCompleted,
    /// A realtime model turn was cancelled.
    #[serde(rename = "llm.turn_cancelled")]
    LlmTurnCancelled,
    /// ASR voice activity started.
    #[serde(rename = "asr.vad_started")]
    AsrVadStarted,
    /// ASR voice activity ended.
    #[serde(rename = "asr.vad_ended")]
    AsrVadEnded,
    /// ASR emitted a revisable partial transcript.
    #[serde(rename = "asr.partial")]
    AsrPartial,
    /// ASR emitted the current final transcript.
    #[serde(rename = "asr.final")]
    AsrFinal,
    /// ASR replaced a final result inside an allowed enhancement window.
    #[serde(rename = "asr.final_update")]
    AsrFinalUpdate,
    /// A TTS audio stream started.
    #[serde(rename = "tts.audio_started")]
    TtsAudioStarted,
    /// Metadata for a TTS binary audio chunk.
    #[serde(rename = "tts.audio_chunk")]
    TtsAudioChunk,
    /// A TTS text-to-audio position marker.
    #[serde(rename = "tts.mark")]
    TtsMark,
    /// A TTS audio stream ended.
    #[serde(rename = "tts.audio_ended")]
    TtsAudioEnded,
}

/// Canonical event envelope shared by WebSocket messages and fixture assertions.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct EventEnvelope<T> {
    /// Stable event type.
    #[serde(rename = "type")]
    pub event_type: EventType,
    /// Globally unique event identifier.
    pub event_id: EventId,
    /// Associated QingYin session identifier.
    pub session_id: SessionId,
    /// Strictly increasing sequence inside the session stream.
    pub sequence: EventSequence,
    /// Service-generated event timestamp.
    pub occurred_at_ms: TimestampMs,
    /// Cross-service trace identifier.
    pub trace_id: TraceId,
    /// Type-specific event payload.
    pub data: T,
    /// Event schema version.
    pub schema_version: String,
}

#[cfg(test)]
mod tests {
    use super::{
        AudioCodec, CanonicalError, ErrorCategory, ErrorCode, EventType, ResourceId, SessionId,
        SessionState, TaskKind,
    };

    #[test]
    fn resource_ids_enforce_contract_length_and_semantic_types() {
        assert!(ResourceId::new("ses_abc1").is_some());
        assert!(SessionId::new("ses_abc1").is_some());
        assert!(ResourceId::new("short").is_none());
        assert!(ResourceId::new("x".repeat(129)).is_none());
        assert!(serde_json::from_str::<SessionId>("\"short\"").is_err());
    }

    #[test]
    fn session_state_machine_allows_only_forward_or_terminal_transitions() {
        assert!(SessionState::Created.can_transition_to(SessionState::Authorized));
        assert!(SessionState::Active.can_transition_to(SessionState::Retrying));
        assert!(SessionState::Retrying.can_transition_to(SessionState::Active));
        assert!(SessionState::Draining.can_transition_to(SessionState::Completed));
        assert!(SessionState::Connecting.can_transition_to(SessionState::Failed));

        assert!(!SessionState::Created.can_transition_to(SessionState::Leased));
        assert!(!SessionState::Active.can_transition_to(SessionState::Completed));
        assert!(!SessionState::Completed.can_transition_to(SessionState::Active));
        assert!(!SessionState::Cancelled.can_transition_to(SessionState::Failed));
    }

    #[test]
    fn canonical_error_derives_category_and_retryability() {
        let unavailable =
            CanonicalError::new(ErrorCode::ProviderUnavailable, "provider unavailable");
        assert_eq!(unavailable.category(), ErrorCategory::Upstream);
        assert!(unavailable.retryable);

        let denied = CanonicalError::new(ErrorCode::PermissionDenied, "permission denied");
        assert_eq!(denied.category(), ErrorCategory::Auth);
        assert!(!denied.retryable);
    }

    #[test]
    fn canonical_wire_names_match_frozen_contracts() {
        assert!(matches!(
            serde_json::to_value(TaskKind::Realtime),
            Ok(value) if value == serde_json::json!("realtime")
        ));
        assert!(matches!(
            serde_json::to_value(AudioCodec::PcmS16Le),
            Ok(value) if value == serde_json::json!("pcm_s16le")
        ));
        assert!(matches!(
            serde_json::to_value(EventType::AsrFinalUpdate),
            Ok(value) if value == serde_json::json!("asr.final_update")
        ));
    }
}
