//! Canonical IDs, status values, errors, events, and trace-safe primitive types.

use std::fmt;

/// Stable fixture schema version for the first public contract generation.
pub const SCHEMA_VERSION_V1: &str = "v1";

/// Opaque resource identifier used in public contracts.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub struct ResourceId(String);

impl ResourceId {
    /// Creates an ID only when it has the expected prefix and non-empty entropy suffix.
    #[must_use]
    pub fn new(prefix: &str, value: impl Into<String>) -> Option<Self> {
        let value = value.into();
        let suffix = value.strip_prefix(prefix)?;
        (!suffix.is_empty() && suffix.chars().all(is_id_char)).then_some(Self(value))
    }

    /// Returns the identifier as a string slice.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ResourceId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// Public `QingYin` session identifier.
pub type SessionId = ResourceId;

/// Public `QingYin` event identifier.
pub type EventId = ResourceId;

/// Cross-service trace identifier.
pub type TraceId = ResourceId;

/// Milliseconds since the Unix epoch, generated by the service for public events.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct TimestampMs(pub u64);

/// Sequence number that is strictly increasing inside one session stream.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct EventSequence(pub u64);

/// Canonical terminal and non-terminal session states.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SessionStatus {
    /// Lease persisted and ticket issuance is allowed.
    Leased,
    /// Relay channel accepted and provider setup completed.
    Active,
    /// Session completed normally.
    Completed,
    /// Session was cancelled by client or control API.
    Cancelled,
    /// Session failed with a canonical error.
    Failed,
}

/// M1-supported task families.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TaskKind {
    /// Real-time ASR over WebSocket.
    AsrRealtime,
    /// Streaming TTS over WebSocket or HTTP.
    TtsStreaming,
}

/// Canonical error category from the module 12 error dictionary.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ErrorCategory {
    /// Authentication or authorization failure.
    Auth,
    /// Quota or rate limit failure.
    Quota,
    /// Request validation failure.
    Validation,
    /// Policy denial.
    Policy,
    /// Session lifecycle failure.
    Session,
    /// Provider or upstream failure.
    Upstream,
    /// Capacity admission failure.
    Capacity,
    /// Internal service failure.
    Internal,
}

/// Canonical error code from the module 12 error dictionary.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ErrorCode {
    /// Invalid `QingYin` credential.
    AuthInvalid,
    /// Authenticated principal does not have the required permission.
    PermissionDenied,
    /// Tenant or provider quota was exhausted.
    QuotaExhausted,
    /// Rate limit was exceeded.
    RateLimited,
    /// Requested task, codec, language, or profile is unsupported.
    UnsupportedCapability,
    /// Request body, enum, idempotency key, or frame is invalid.
    InvalidRequest,
    /// Audio encoding, order, or rate is invalid.
    InvalidAudio,
    /// Hard policy denied the request.
    PolicyDenied,
    /// Ticket or lease expired.
    SessionExpired,
    /// Provider is unavailable before a safe boundary.
    ProviderUnavailable,
    /// Provider timed out.
    ProviderTimeout,
    /// Provider emitted invalid protocol data.
    ProviderProtocolError,
    /// Gateway or provider capacity is exhausted.
    CapacityExceeded,
    /// Session was cancelled.
    Cancelled,
    /// Unexpected internal error.
    InternalError,
}

impl ErrorCode {
    /// Returns the stable category for this code.
    #[must_use]
    pub const fn category(self) -> ErrorCategory {
        match self {
            Self::AuthInvalid | Self::PermissionDenied => ErrorCategory::Auth,
            Self::QuotaExhausted | Self::RateLimited => ErrorCategory::Quota,
            Self::UnsupportedCapability | Self::InvalidRequest | Self::InvalidAudio => {
                ErrorCategory::Validation
            }
            Self::PolicyDenied => ErrorCategory::Policy,
            Self::SessionExpired | Self::Cancelled => ErrorCategory::Session,
            Self::ProviderUnavailable | Self::ProviderTimeout | Self::ProviderProtocolError => {
                ErrorCategory::Upstream
            }
            Self::CapacityExceeded => ErrorCategory::Capacity,
            Self::InternalError => ErrorCategory::Internal,
        }
    }

    /// Returns whether retry is safe by default for this canonical code.
    #[must_use]
    pub const fn default_retryable(self) -> bool {
        matches!(
            self,
            Self::QuotaExhausted
                | Self::RateLimited
                | Self::ProviderUnavailable
                | Self::CapacityExceeded
                | Self::InternalError
        )
    }
}

/// API and stream-safe canonical error shape.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ApiError {
    /// Stable canonical code.
    pub code: ErrorCode,
    /// Stable error category derived from the code.
    pub category: ErrorCategory,
    /// Developer-facing sanitized message.
    pub message: String,
    /// Whether retry is safe for this occurrence.
    pub retryable: bool,
    /// Optional retry hint in milliseconds.
    pub retry_after_ms: Option<u64>,
    /// Optional opaque diagnostic identifier.
    pub diagnostic_id: Option<String>,
}

impl ApiError {
    /// Builds a canonical error with derived category and default retryability.
    #[must_use]
    pub fn new(code: ErrorCode, message: impl Into<String>) -> Self {
        Self {
            code,
            category: code.category(),
            message: message.into(),
            retryable: code.default_retryable(),
            retry_after_ms: None,
            diagnostic_id: None,
        }
    }
}

/// Canonical event type names emitted by the M1 ASR/TTS relay boundary.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EventType {
    /// Session is ready to send or receive stream frames.
    SessionReady,
    /// Session completed normally.
    SessionCompleted,
    /// Session failed with a canonical error.
    SessionError,
    /// Recoverable flow-control warning.
    FlowWarning,
    /// ASR voice activity started.
    AsrVadStarted,
    /// ASR partial transcript.
    AsrPartial,
    /// ASR final transcript.
    AsrFinal,
    /// TTS audio stream started.
    TtsAudioStarted,
    /// TTS audio chunk metadata.
    TtsAudioChunk,
    /// TTS audio stream ended.
    TtsAudioEnded,
}

/// Canonical event envelope shared by WebSocket and fixture assertions.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EventEnvelope<T> {
    /// Stable event type.
    pub event_type: EventType,
    /// Globally unique event identifier.
    pub event_id: EventId,
    /// Associated `QingYin` session identifier.
    pub session_id: SessionId,
    /// Strictly increasing sequence inside the session stream.
    pub sequence: EventSequence,
    /// Service-generated event timestamp.
    pub occurred_at_ms: TimestampMs,
    /// Cross-service trace identifier.
    pub trace_id: TraceId,
    /// Type-specific event payload.
    pub data: T,
    /// Event schema version.
    pub schema_version: String,
}

fn is_id_char(value: char) -> bool {
    value.is_ascii_alphanumeric() || matches!(value, '_' | '-')
}

#[cfg(test)]
mod tests {
    use super::{ApiError, ErrorCategory, ErrorCode, ResourceId};

    #[test]
    fn resource_id_requires_expected_prefix_and_suffix() {
        assert!(ResourceId::new("ses_", "ses_abc-123").is_some());
        assert!(ResourceId::new("ses_", "evt_abc-123").is_none());
        assert!(ResourceId::new("ses_", "ses_").is_none());
        assert!(ResourceId::new("ses_", "ses_bad/value").is_none());
    }

    #[test]
    fn api_error_derives_category_and_retryability() {
        let error = ApiError::new(ErrorCode::ProviderUnavailable, "provider unavailable");
        assert_eq!(error.category, ErrorCategory::Upstream);
        assert!(error.retryable);

        let denied = ApiError::new(ErrorCode::PermissionDenied, "permission denied");
        assert_eq!(denied.category, ErrorCategory::Auth);
        assert!(!denied.retryable);
    }
}
